version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aura-postgres
    environment:
      POSTGRES_USER: aura
      POSTGRES_PASSWORD: ${DB_PASSWORD:-localdev}
      POSTGRES_DB: aura_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aura"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: aura-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-localdev}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: aura-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__TELEMETRY_DISABLED: true

volumes:
  postgres_data:
  redis_data:
  qdrant_data:

networks:
  default:
    name: aura-network